Specify minimum wisper version
I am trying to use this gem with wisper v1.4.0, but it had no method named `configure` back then.
```
Failure/Error: report = Wisper::Visualize.report
     
     NoMethodError:
       undefined method `configure' for Wisper:Module

     # /home/me/.rvm/gems/ruby-2.2.7/gems/wisper-visualize-0.0.1/lib/wisper/visualize/report.rb:6:in `initialize'
     # /home/me/.rvm/gems/ruby-2.2.7/gems/wisper-visualize-0.0.1/lib/wisper/visualize.rb:11:in `new'
     # /home/me/.rvm/gems/ruby-2.2.7/gems/wisper-visualize-0.0.1/lib/wisper/visualize.rb:11:in `report'
     # ./spec/spec_helper.rb:83:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:78:in `block (3 levels) in <top (required)>'
```